apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: voting-app
    name: postgres-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: voting-app
    name: postgres