apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: back-end
    app: voting-app

spec:
  containers:
    - name:  postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSSWORD
        value: "postgres"
      - name: POSTGRES_HOST_AUTH_METHOD
        value: "trust"