apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deployment
  labels:
    app: voting-app
    name: results-app-deployment

spec:
  selector:
    matchLabels:
      app: voting-app
      name: voting-appresult
  template:
    metadata:
      name: voting-appresult
      labels:
        name: voting-appresult
        app: voting-app
    spec:
      containers:
        - name:  voting-appresult
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80  
  replicas: 1

