apiVersion: v1
kind: Service
metadata:
  name: votingapp-result
  labels:
    app: voting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    app: voting-app
    name: voting-appresult