apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: back-end
    name: redis
    app: voting-app

spec:
  containers:
    - name:  redis
      image: redis
      ports:
        - containerPort: 6379