apiVersion: v1
kind: Pod
metadata:
  name: voting-appresult
  labels:
    tier: front-end
    app: voting-app
    name: votingapp-result

spec:
  containers:
    - name:  votingapp-result
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
