apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    tier: front-end
    app: voting-app
    name: voting-app

spec:
  containers:
    - name:  votingapp-vote
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
