apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    tier: back-end
    app: voting-app

spec:
  containers:
    - name:  votingapp-worker
      image: kodekloud/examplevotingapp_worker:v1

